iFlyChatBotUI/Controllers/AdminController.cs
using Hangfire;
using iFlyChatBot.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace iFlyChatBot.UI.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult Index()
        {
            //RecurringJob.AddOrUpdate(() => Console.Write("Easy!"), Cron.Minutely);
            //RecurringJob.AddOrUpdate(() => Debug.WriteLine("Easy!"), Cron.Minutely);
            return View();
        }

        public ActionResult SiteUser(int id, int uid)
        {
            iFlyChatBot.SiteUserUpdate(id, uid);
            return RedirectToAction("Index");
        }

        public ActionResult Sites()
        {
            return View();
        }
        public ActionResult SiteDetail(int id = -1)
        {
            if (id == -1) return View(new iFlyChat_Site());
            return View(Config.Sites.Find(x => x.Id == id));
        }

        [HttpPost]
        public ActionResult SaveSite(iFlyChat_Site model)
        {
            iFlyChatBot.SaveSite(model);
            return RedirectToAction("Sites");
        }

        public ActionResult DeleteSite(int id)
        {
            iFlyChatBot.DeleteSite(id);
            return RedirectToAction("Sites");
        }

        public ActionResult Users()
        {
            return View();
        }
        public ActionResult UserDetail(int id = -1)
        {
            if (id == -1) return View(new iFlyChat_User());
            return View(Config.Users.Find(x => x.Id == id));
        }

        [HttpPost]
        public ActionResult SaveUser(iFlyChat_User model)
        {
            iFlyChatBot.SaveUser(model);
            return RedirectToAction("Users");
        }

        public ActionResult DeleteUser(int id)
        {
            iFlyChatBot.DeleteUser(id);
            return RedirectToAction("Users");
        }

        public ActionResult Sources()
        {
            return View();
        }

        public ActionResult SourceDetail(int id = -1)
        {
            if (id == -1) return View(new iFlyChat_Source());
            return View(Config.Sources.Find(x => x.Id == id));
        }
        
        [HttpPost]
        public ActionResult SaveSource(iFlyChat_Source model)
        {
            iFlyChatBot.SaveSource(model);
            return RedirectToAction("Sources");
        }
        public ActionResult DeleteSource(int id)
        {
            iFlyChatBot.DeleteSource(id);
            return RedirectToAction("Sources");
        }

        public ActionResult Readers() {
            return View();
        }

        public ActionResult ReaderDetail(int id = -1) {
            if (id == -1) return View(new iFlyChat_Reader_Twitter());
            return View(Config.TwtterReaders.Find(x => x.Id == id));
        }

        [HttpPost]
        public ActionResult SaveReader(iFlyChat_Reader_Twitter model) {
            iFlyChatBot.SaveReader(model);
            return RedirectToAction("Readers");
        }
        public ActionResult DeleteReader(int id) {
            iFlyChatBot.DeleteReader(id);
            return RedirectToAction("Readers");
        }

    }
}

iFlyChatBotUI/Controllers/BotController.cs
using Hangfire;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace iFlyChatBot.UI.Controllers
{
    public class BotController : Controller
    {
        // GET: Bot
        public ActionResult Start()
        {
            //if(!iFlyChatBot.Running) 
            RecurringJob.AddOrUpdate(() => MvcApplication.bot.Update(), Cron.Minutely);
            //MvcApplication.bot.Update();

            iFlyChatBot.Running = true;
            return RedirectToAction("Index", "Admin");
//            return View("~/Views/Admin/Index");
        }
        public ActionResult Stop()
        {
            RecurringJob.RemoveIfExists("botproc");            
            iFlyChatBot.Running = false;
            return RedirectToAction("Index", "Admin");
            //return View("~/Views/Admin/Index");
        }
        public ActionResult Configure()
        {
            return RedirectToAction("Index", "Admin");
//            return View("~/Views/Admin/Index");
        }

        public ActionResult SendMessage(int UserId, int SiteId, string message) {
            iFlyChatBot.PostFromDashboard(SiteId, UserId, message);
            return RedirectToAction("Users", "Admin");
        }
    }
}

iFlyChatBotUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace iFlyChatBot.UI.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
        //    var bot = new iFlyChatBot();
            return View();
        }
    }
}

iFlyChatBotUI/Views/Admin/Index.cshtml
@model iFlyChatBot
@{
    ViewBag.Title = "Index";
}
<style>
    textarea {
        font-size: 10px;
        width: 100%;
        height: 600px;
    }
</style>
@section BotControlls {
<div style="font-size: 18px; letter-spacing:5px; margin-top:10px;">
    <!-- pretend an enclosing class has big font size -->
    @if (iFlyChatBot.Running)
    {
        <span class="label label-success">On!</span>
        @Html.ActionLink("stop", "Stop", "Bot", null, new { @class = "btn btn-link", @style = "letter-spacing: normal; color:red; font-weight:bolder;" })
    }
    else
    {
        <span class="label label-danger">Off!</span>
        @Html.ActionLink("start", "Start", "Bot", null, new { @class = "btn btn-link", @style = "letter-spacing: normal; color:green; font-weight:bolder;" })
    }

</div>


}
<p>Select @Html.ActionLink("Sites", "Sites"), @Html.ActionLink("Users", "Users") or @Html.ActionLink("Sources", "Sources") to configure.</p>

<div class="row">
    <div class="col-md-6">
@foreach (var s in Config.Sites)
{
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title"><span class="glyphicon glyphicon-globe"></span> @s.Name</h3>
            </div>
            <div class="panel-body">
                @if (Config.SitesUsers.Any(x => x.SiteId == s.Id))
                {
                    <table class="table table-condensed table-hover">
                        <thead>
                            <tr>
                                <th>Active Users</th>
                                <th style="text-align:center;"></th>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach (var su in Config.SitesUsers.Where(x => x.SiteId == s.Id))
                        {
                            var user = Config.Users.Find(y => y.Id == su.UserId);
                            var source = Config.Sources.Find(z => z.Id == user.SourceId);
                            var sourceDisplay = source == null ? "None" : source.Username;
                            <tr>
                                <td><span class="glyphicon glyphicon-user" style="color:#3a87ad;"></span> @user.Name [@sourceDisplay]</td>
                                <td>@Html.ActionLink("Remove", "SiteUser", new { id = s.Id, uid = user.Id })</td>
                            </tr>
                        }
                        </tbody>
                    
                    </table>
                } else
                {
                    <p>No users added for this site.</p>
                }
                <table class="table table-condensed table-hover">
                    <thead>
                        <tr>
                            <th>Available Users</th>
                            <th style="text-align:center;"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach(var u in Config.Users.Where(x => !Config.SitesUsers.Where(z => z.SiteId == s.Id).Select(g => g.UserId).Contains(x.Id))) { 
                            <tr>
                                <td><span class="glyphicon glyphicon-user" style="color:#3a87ad;"></span> @u.Name</td>
                                <td>@Html.ActionLink("Add", "SiteUser", new { id = s.Id, uid = u.Id })</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
}
    </div>
    <div class="col-md-4">

    </div>
</div>
@*<div class="row">
    <div class="col-md-2">
        @if (iFlyChatBot.Running)
        {
            <button type="button" class="btn btn-danger">Stop</button>
        }
        else
        {
            <button type="button" class="btn btn-success">Start</button>
        }
    </div>
</div>*@
@*@using (Html.BeginForm("Index", "Home", FormMethod.Post))
{

        <div class="row">
                <div class="col-md-6">
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <h3 class="panel-title">Sites</h3>
                        </div>
                        <div class="panel-body">
                            <table class="table table-condensed table-hover table-bordered">
                                <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>Name</th>
                                        <th style="text-align:center;">Room</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var s in Config.Sites)
                                    {     
                                        <tr>
                                            <td><a href="#">#@s.Id</a></td>
                                            <td>@s.Name</td>
                                            <td>@s.RoomId</td>
                                        </tr>
                                    }
                                </tbody>
                            </table>

                        </div>
                    </div>
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <h3 class="panel-title">Sources</h3>
                        </div>
                        <div class="panel-body">
                            <table class="table table-condensed table-hover table-bordered">
                                <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>Type</th>
                                        <th>Name</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var s in Config.Sources)
                                    {
                                        <tr>
                                            <td>@s.Id</td>
                                            <td>@s.Type</td>
                                            <td>@s.Username</td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>


                </div>


            }*@

iFlyChatBotUI/Views/Admin/ReaderDetail.cshtml
@using iFlyChatBot.Models
@model iFlyChat_Reader_Twitter
@{
    ViewBag.Title = "ReaderDetail";
}

<h2><span class="glyphicon glyphicon-book"></span> @Model.Username</h2>

<div class="row">
    <div class="col-md-6">
        @using (Html.BeginForm("SaveReader", "Admin", FormMethod.Post)) {
            @Html.HiddenFor(m => m.Id)
            <div class="form-group">
                <div class="row">                    
                    <div class="col-md-4">
                        @Html.LabelFor(m => m.Username, new { @class = "control-label" })
                        @Html.TextBoxFor(m => m.Username, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Username, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-4">
                        @Html.LabelFor(m => m.Password, new { @class = "control-label" })
                        @Html.TextBoxFor(m => m.Password, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    
                    <div class="col-md-4">
                        @Html.LabelFor(m => m.Type, new { @class = "control-label" })
                        @*@Html.TextBoxFor(m => m.Type, new { @class = "form-control" })*@
                        @Html.DropDownListFor(x => x.Type, new SelectListItem[]{
                            new SelectListItem() {Text = "Twitter", Value="Twitter"}
//                            new SelectListItem() {Text = "Facebook", Value="Facebook"},
//                            new SelectListItem() {Text = "Instagram", Value="Instagram"}
                        }, new { @class = "form-control"})
                        @Html.ValidationMessageFor(m => m.Type, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        @Html.LabelFor(m => m.twitter_accessToken, new { @class = "control-label" })
                        @Html.TextBoxFor(m => m.twitter_accessToken, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.twitter_accessToken, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        @Html.LabelFor(m => m.twitter_accessTokenSecret, new { @class = "control-label" })
                        @Html.TextBoxFor(m => m.twitter_accessTokenSecret, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.twitter_accessTokenSecret, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        @Html.LabelFor(m => m.twitter_consumerKey, new { @class = "control-label" })
                        @Html.TextBoxFor(m => m.twitter_consumerKey, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.twitter_consumerKey, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        @Html.LabelFor(m => m.twitter_consumerSecret, new { @class = "control-label" })
                        @Html.TextBoxFor(m => m.twitter_consumerSecret, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.twitter_consumerSecret, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="row">
                    <div class="col-md-2">
                        <input type="submit" value="Save" class="btn btn-primary" />
                    </div>
                </div>
            </div>
            @*@Html.EditorForModel()
            <input class="btn-danger" type="submit" name="Update" value="Update" />*@
        }
    </div>


</div>

iFlyChatBotUI/Views/Admin/Readers.cshtml
@{
    ViewBag.Title = "Readers";
}
<style>
    ul {

    }
</style>
<h3 style="color:#3a87ad;"><span class="glyphicon glyphicon-book"></span> Readers</h3>

<div class="row">
    <div class="col-md-12">
        <table class="table table-condensed table-hover table-bordered">
            <thead>
                <tr>
                    <th>Channel</th>
                    <th>Name</th>
                    <th>Load(#Sources)</th>
                    <th>Messages</th>
                    <th style="text-align:center;"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var s in Config.TwtterReaders) {
                    <tr>
                        <td>@s.Type</td>
                        <td>
                            <a href="http://twitter.com/@s.Username"><img style="max-height:24px;" src="@Url.Content("~/Content/twitter.png")"> @s.Username</a>
                        </td>
                        @{
                            var sources = s.GetSources();
                        }
                        <td>
                            @sources.Count
                            <ul style="list-style:none;">
                                @foreach (var so in sources) {
                                    <li>
                                        <a href="http://twitter.com/@so.Username"><img style="max-height:24px;" src="@Url.Content("~/Content/twitter.png")"> @so.Username</a>
                                         
                                        <ul style="list-style:none;">
                                            @foreach (var si in Config.Users.Where(x => x.SourceId == so.Id)) {
                                                <li>
                                                    <a href="@Url.Action("UserDetail", "Admin", new { id = @si.Id })"><img style="max-height:24px;" src="@Url.Content("~/Content/iflychat.png")"> @si.Name</a>
                                            </li>
                                            }
                                        </ul>
                                    </li>

                                }
                            </ul>
                        </td>
                        <td>
                            <p>Messages</p>
                            @{ 
                                var messages = s.GetMessages();
                            }
                            <table class="table table-condensed table-hover" style="font-size:10px;">
                                <thead>
                                    <tr>
                                        <th>Time</th>
                                        <th>Handle</th>
                                        <th>Message</th>
                                        <th style="text-align:center;"></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var m in messages) {
                                        var twitterHandle = Config.Sources.FirstOrDefault(x => x.Id == m.SourceId);
                                        if(twitterHandle == null) { continue; }
                                        <tr>
                                            <td>
                                                @m.CreatedOn.ToShortTimeString()
                                            </td>
                                            <td>
                                               @twitterHandle.Username
                                            </td>
                                            <td>
                                                @m.Text
                                            </td>
                                            <td>
                                                Act1
                                                Act2
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </td>
                        <td>
                            @Html.ActionLink("Delete", "DeleteReader", new { id = s.Id })
                            @Html.ActionLink("Edit", "ReaderDetail", new { id = s.Id })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        @Html.ActionLink("New Twitter-Reader","ReaderDetail", new { id = -1 })
    </div>
</div>

iFlyChatBotUI/Views/Admin/SiteDetail.cshtml
@using iFlyChatBot.Models
@model iFlyChat_Site
@{
    ViewBag.Title = "SiteDetail";
}

<h2><span class="glyphicon glyphicon-globe"></span> @Model.Name</h2>

<div class="row">
    @*<div class="col-md-4">
@using (Html.BeginForm("SaveSite", "Admin", FormMethod.Post))
{
    @Html.EditorForModel()
    <input class="btn-danger" type="submit" name="Update" value="Update" />
}
    </div>*@
    <div class="col-md-6">
        @using (Html.BeginForm("SaveSite", "Admin", FormMethod.Post)) {
            @Html.HiddenFor(m => m.Id)
            <div class="form-group">
                <div class="row">
                    <div class="col-md-10">
                        @Html.LabelFor(m => m.Name, new { @class = "control-label" })
                        @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-2">
                        @Html.LabelFor(m => m.RoomId, new { @class = "control-label" })
                        @Html.TextBoxFor(m => m.RoomId, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.RoomId, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-md-12">
                        @Html.LabelFor(m => m.ApiKey, "iFlyChat RoomId", new { @class = "control-label" })
                        @Html.TextBoxFor(m => m.ApiKey, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.ApiKey, "", new { @class = "text-danger" })
                    </div>
                </div>

            </div>

            <div class="form-group">
                <div class="row">
                    <div class="col-md-2">
                        <input type="submit" value="Save" class="btn btn-primary" />
                    </div>
                </div>
            </div>
            @*@Html.EditorForModel()
                <input class="btn-danger" type="submit" name="Update" value="Update" />*@
        }
    </div>
</div>

iFlyChatBotUI/Views/Admin/Sites.cshtml
@{
    ViewBag.Title = "Sites";
}

<h3 style="color:#3a87ad;"><span class="glyphicon glyphicon-globe"></span> Sites</h3>

<div class="row">
    <div class="col-md-6">
                <table class="table table-condensed table-hover">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th style="text-align:center;">Room</th>
                            <th style="text-align:center;"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var s in Config.Sites)
                        {
                            <tr>
                                <td>@s.Name</td>
                                <td>@s.RoomId</td>
                                <td>
                                    @Html.ActionLink("Delete", "DeleteSite", new { id = s.Id })
                                    @Html.ActionLink("Edit", "SiteDetail", new { id = s.Id })
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            @Html.ActionLink("New", "SiteDetail", new { id = -1 })
    </div>
</div>

iFlyChatBotUI/Views/Admin/SourceDetail.cshtml
@using iFlyChatBot.Models
@model iFlyChat_Source
@{
    ViewBag.Title = "SourceDetail";
}

<h2><span class="glyphicon glyphicon-download-alt"></span> @Model.Username</h2>

<div class="row">
    @*<div class="col-md-4">
        @using (Html.BeginForm("SaveSource", "Admin", FormMethod.Post))
        {
            @Html.EditorForModel()
            <input class="btn-danger" type="submit" name="Update" value="Update" />
        }
    </div>*@
    <div class="col-md-6">
        @using (Html.BeginForm("SaveSource", "Admin", FormMethod.Post)) {
            @Html.HiddenFor(m => m.Id)
            @Html.HiddenFor(m => m.SinceId)
            <div class="form-group">
                <div class="row">
                    <div class="col-md-4">
                        @Html.LabelFor(m => m.Username, new { @class = "control-label" })
                        @Html.TextBoxFor(m => m.Username, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Username, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-4">
                        @Html.LabelFor(m => m.ReaderId, new { @class = "control-label" })
                        @{ 
                            SelectListItem selListItem = new SelectListItem() { Value = "null", Text = "Select One" };
                            List<SelectListItem> readers = new List<SelectListItem>();
                            readers.Add(selListItem);
                            var treaders = Config.TwtterReaders.Select(x =>
                                                        new SelectListItem() {
                                                            Text = x.Username,
                                                            Value = x.Id.ToString()
                                                        }
                                                    );
                            var rTemp = readers.ToList();
                            readers.AddRange(treaders);
                        }
                        @Html.DropDownListFor(x => x.ReaderId, readers, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.ReaderId, "", new { @class = "text-danger" })

                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-md-2">
                        <input type="submit" value="Save" class="btn btn-primary" />
                    </div>
                    <div class="col-md-4">
                        <p>@Model.LastUpdate</p>
                    </div>
                </div>
            </div>
            @*@Html.EditorForModel()
            <input class="btn-danger" type="submit" name="Update" value="Update" />*@
        }
    </div>
</div>

iFlyChatBotUI/Views/Admin/Users.cshtml
@{
    ViewBag.Title = "Users";
}

<h3 style="color:#3a87ad;"><span class="glyphicon glyphicon-user"></span> Users</h3>

<div class="row">
    <div class="col-md-10">
        <table class="table table-condensed table-hover">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Source</th>
                    <th>Active</th>
                    <th>Image</th>
                    <th style="text-align:center;"></th>
                    <th>Chat</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var s in Config.Users)
                {
                    <tr>
                        <td>
                            <a href="#"><img style="max-height:24px;" src="@Url.Content("~/Content/iflychat.png")"> @s.Name</a>
                        </td>
                        <td>
                            @{ 
                                var source = Config.Sources.FirstOrDefault(x => x.Id == s.SourceId);
                            }
                            @if (source != null) {
                                <a href="http://twitter.com/@source.Username"><img style="max-height:24px;" src="@Url.Content("~/Content/twitter.png")"> @source.Username</a>
                            } else {
                                <a href="#">Invalid</a>
                            }
                        </td>
                        @if (s.Active) {
                            <td><span class="label label-success">Y</span></td>
                        } else {
                            <td><span class="label label-default">N</span></td>
                        }
                        
                        <td><img src="@s.Image" alt="profile_pic" style="max-height:32px;" /></td>
                        <td>
                            @Html.ActionLink("Delete", "DeleteUser", new { id = s.Id })
                            @Html.ActionLink("Edit", "UserDetail", new { id = s.Id })
                        </td>
                        <td>
                            @using (Html.BeginForm("SendMessage", "Bot", FormMethod.Post)) {
                                @Html.Hidden("UserId", s.Id)                                

                                var sites = Config.Sites.Select(x =>
                                    new SelectListItem() {
                                        Text = x.Name,
                                        Value = x.Id.ToString()
                                    }
                                );
                                @Html.DropDownList("SiteId", sites, new { @class = "form-control" })

                                @Html.TextBox("message", "", new { @class = "form-control" })
                                <div class="form-group">
                                    <div class="row">
                                        <div class="col-md-2">
                                            <input type="submit" value="Send" class="btn btn-primary" />
                                        </div>
                                    </div>
                                </div>
                                }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        @Html.ActionLink("New", "UserDetail", new { id = -1 })
    </div>
</div>

iFlyChatBotUI/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}